apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: docgen
  name: docgen
spec:
  selector:
    matchLabels:
      io.kompose.service: docgen
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: docgen
    spec:
      containers:
        - env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: docgen-env
          image: gcr.io/testproject-252007/docgenerator:latest
          name: docgen
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
